# Generated by Django 4.1.6 on 2023-02-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date_de_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
