# Generated by Django 4.1.6 on 2023-02-03 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flight_date_de_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_de_depart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 3, 22, 32, 56, 884865), null=True),
        ),
    ]
